SELECT
    EXTRACT(YEAR FROM s.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM s.SALES_DATE) AS MONTH,
    u.GENDER,
    COUNT(distinct u.user_id) AS USERS
FROM
    USER_INFO u
    JOIN ONLINE_SALE s ON u.USER_ID = s.USER_ID
WHERE
    u.GENDER IS NOT NULL
GROUP BY
    EXTRACT(YEAR FROM s.SALES_DATE),
    EXTRACT(MONTH FROM s.SALES_DATE),
    u.GENDER
ORDER BY
    YEAR,
    MONTH,
    GENDER;